brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
    path(
        "<int:pk>/edit/", TodoListUpdateView.as_view(), name="todo_list_update"
    ),
    path(
        "<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/", TodoItemCreateView.as_view(), name="todo_item_create"
    ),
    path("items/<int:pk>/edit/", TodoItemUpdateView.as_view(), name="todo_item_update"),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(default=None, blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from todos.models import TodoList, TodoItem


class TodoListListView(ListView):
    model = TodoList
    template_name = "todolists/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todolists/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todolists/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

    # success_url = reverse_lazy("todo_list_detail")


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todolists/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

    # success_url = reverse_lazy("todo_list_list")


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todolists/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todoitems/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

    # success_url = reverse_lazy("todo_list_detail")


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todoitems/update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

    # success_url = reverse_lazy("todo_list_detail")

todos/templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>To Do Lists</title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

todos/templates/todoitems/create.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Create a new item</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

todos/templates/todoitems/update.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Update item</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <div>
        <button>Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

todos/templates/todolists/create.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Create a new list</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

todos/templates/todolists/delete.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Are you sure?</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

      <div>
        <button>Delete</button>
      </div>
    </form>
  </main>
{% endblock content %}

todos/templates/todolists/detail.html
{% extends "base.html" %}
{% block content %}
<main>
    <div>

        <h1>{{ todolist.name }}</h1>
            <p>
                <a href="{% url "todo_list_update" todolist.id %}">Edit</a>
                <a href="{% url "todo_list_delete" todolist.id %}">Delete</a>
            </p>
        <h2>Tasks</h2>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due date</th>
                </tr>
            </thead>
            {% for item in todolist.items.all %}
            <tbody>
                <tr>
                    <td>
                        <a href="{% url "todo_item_update" item.pk %}">{{item.task}}</a>
                    </td>
                    <td>{{item.due_date}}</td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</main>
{% endblock content %}

todos/templates/todolists/list.html
{% extends "base.html" %}
{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
            <p>
                <a href="{% url "todo_list_create" %}">Create a new list</a>
            </p>
            <p>
                <a href="{% url "todo_item_create" %}">Create a new item</a>
            </p>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
            </thead>
            <tbody>
            {% for list in todolist_list %}
                <tr>
                    <td>
                        <a href="{% url "todo_list_detail" list.pk %}">{{list.name}}</a>
                    </td>
                    <td>{{list.items.all|length}}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</main>
{% endblock content %}

todos/templates/todolists/update.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Update list</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

      <div>
        <button>Update</button>
      </div>
    </form>
  </main>
{% endblock content %}